### ISSUE TITLE
Add workaround for, and fetch ferry data post 7. feb 2024

### ISSUE THREAD

**Issue by tfk-kaare** [TromsFylkestrafikk/ragnarok-mobitech#4]
Mobitech has changed the folder structure after feb 7th, causing imported data to fail/halt/choke. There need to be a mechanism that detects and act on this.

**Comment by tft-kyrre** [comment]
A mechanism to handle the old and new versions with different external folder structure has always been there and I'm unable to reproduce any fail/halt/choke situation. However, it is worth mentioning that the daily chunk may contain 1000 - 3000 small files and therefore take a long time to complete. 10 to 15 minutes is quite normal in my experience.

I have removed the warning about missing (statistics) files since this would show up for every downloaded chunk, but for missing transaction files the warning will still be logged.

**Comment by tfk-kaare** [comment]
We should reach out to Mobitech asking politely for daily zipped files. I doesn't make sense to download so many small files.

That is a follow-up issue.
